pipeline {
    agent any


options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {


        stage('Pull image'){
            steps{
                bat '''
                        docker pull adasirotkina/mle_lab1:latest
                '''
            }
        }

        stage('Run container'){
            steps{
                bat '''
                        docker run --name mle-lab1 -p 80:5556 -d adasirotkina/mle_lab1:latest
                        echo "Succes run"
                '''
            }
        }
	}

    post {
        always {
            bat 'docker stop mle-lab1 && docker logout'
        }
    }
}